repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["-l", "120", "--target-version=py311"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
  - repo: local
    hooks:
    -   id: poetry_lock_check
        name: Check if poetry lock file is updated
        entry: |
          python -c "
          from poetry.factory import Factory
          l = Factory().create_poetry('.').locker
          if l.is_locked() and l.is_fresh():
            exit(0)
          else:
            print('run `poetry update` to fix')
            exit(1)
          "
        language: python_venv
        additional_dependencies:
          - poetry
        verbose: True
        files: pyproject.toml
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.13.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
          - '@commitlint/ensure'
          - 'commitlint-plugin-function-rules'
