on:
  pull_request:

jobs:
  pre-commit:
    uses: cachuperia/github-reusable-workflows/.github/workflows/pre-commit.yml@v1.1.0
    with:
      python-version: "3.11.8"

  commitlint:
    uses: cachuperia/github-reusable-workflows/.github/workflows/commitlint.yml@v1.1.0

  pytest:
    uses: cachuperia/github-reusable-workflows/.github/workflows/pytest.yml@v1.1.0
    with:
      python-version: "3.11.8"
      run-integration: true

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
      - pytest
    uses: cachuperia/github-reusable-workflows/.github/workflows/approve.yml@v1.1.0
    secrets:
      token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
